### ISSUE TITLE
ZAF v1 deprecation

### ISSUE THREAD

**Issue by russellhoff** [skipjac/Zendesk-Apps#11]
Beggining August 1st, 2017, Zendesk will no longer accept new apps created using ZAF v1. Besides, as of March 1st, 2018 no further updates using v1 will be accepted. 

Consequently, Zendesk is suggesting everybody to start migrating all the apps to the new v1 ZAF framework.

Will it be possible for you @skipjac to migrate your current app?

Thank you in advance!

**Comment by russellhoff** [comment]
Any update on this? Thanks.

**Comment by skipjac** [comment]
Hi Russell which app are you talking about?

**Comment by russellhoff** [comment]
Hi @skipjac ! I'm talking about ConditionalFields' app.

**Comment by skipjac** [comment]
That is now in the app store and has been updated
