### ISSUE TITLE
Any reason why ConditionalFieldsApp isn't apart of a /zendesk repo?

### ISSUE THREAD

**Issue by 3en** [skipjac/Zendesk-Apps#7]
Hey @skipjac,

I always keep expecting this app to be under github.com/zendesk. Any reason why it doesn't have its own repo?

Definitely is a commonly requested app.
- Ben

**Comment by skipjac** [comment]
There is and that is where i have been pushing updates. zendesk/conditional_fields_app

**Comment by 3en** [comment]
Oh (such an idiot </self>). Maybe we should probably change the README so that it's clear that it has moved.

Swear there was some apps that haven't transitioned. Thought this was one of them.

**Comment by skipjac** [comment]
added deprecated comment with pointer to new repo

**Comment by skipjac** [comment]
Adding deprecated comment with pointer to new repo
